# Generated by Django 4.0.2 on 2022-03-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Refugee',
        ),
    ]
