# Generated by Django 4.0.2 on 2022-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_product_category_product_avability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avability',
            field=models.CharField(choices=[('stock', 'stock'), ('out of stock', 'out of stock')], max_length=200, null=True),
        ),
    ]
