# Generated by Django 4.0.2 on 2022-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_product_avability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refugee',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refugee',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='engine_capacity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_fuel',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('avalible', 'avalible')], max_length=200, null=True),
        ),
    ]
