# Generated by Django 4.0.2 on 2022-03-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_refugee_client_rename_refugee_order_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='name',
        ),
    ]
