# Generated by Django 4.0.2 on 2022-03-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_brand_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='engine_capacity',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('available', 'available')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='avability',
            field=models.CharField(choices=[('available', 'available'), ('non-available', 'non-available')], max_length=200, null=True),
        ),
    ]
