# Generated by Django 4.0.2 on 2022-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_product_body_style_product_car_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='body_style',
            field=models.CharField(choices=[('sedan', 'sedan'), ('coupe', 'coupe'), ('convertible', 'convertible'), ('hatchback', 'hatchback'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('combi', 'combi'), ('crossover', 'crossover')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='car_color',
            field=models.CharField(choices=[('sedan', 'sedan'), ('coupe', 'coupe'), ('convertible', 'convertible'), ('hatchback', 'hatchback'), ('SUV', 'SUV'), ('VAN', 'VAN'), ('combi', 'combi'), ('crossover', 'crossover')], max_length=200, null=True),
        ),
    ]
