# Generated by Django 4.0.2 on 2022-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_product_description_alter_product_body_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_color',
            field=models.CharField(choices=[('red', 'red'), ('white', 'white'), ('black', 'black'), ('yellow', 'yellow'), ('green', 'green'), ('pink', 'pink'), ('blue', 'blue'), ('orange', 'orange')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='engine_fuel',
            field=models.CharField(choices=[('diesel', 'diesel'), ('petrol', 'petrol'), ('LPG', 'LPG'), ('EV', 'EV')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Volkswagen', 'Volkswagen')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_model',
            field=models.CharField(choices=[('Passat', 'Passat'), ('Scirocco', 'Scirocco'), ('Golf', 'Golf'), ('Eos', 'Eos'), ('Tuareg', 'Tuareg'), ('Golf Sportsvan', 'Golf Sportsvan'), ('Arteon', 'Arteon'), ('Tiguan', 'Tiguan')], max_length=200, null=True),
        ),
    ]
